// <auto-generated />
using System;
using Accusoft.Api.Data;
using Accusoft.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Accusoft.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "alerta_tipo", new[] { "documento", "envio", "sistema" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "doc_tipo", new[] { "pdf", "docx", "xlsx", "imagem", "arquivo", "outro" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "envio_estado", new[] { "pendente", "entregue", "atraso", "cancelado" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "movimentacao_tipo", new[] { "movimentacao_interna", "reposicao_picking", "ajuste", "inventario_parcial", "entrada", "saida" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_role", new[] { "admin", "user" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "user_status", new[] { "ativo", "inativo" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Accusoft.Api.Models.Alerta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<string>("Detalhe")
                        .HasColumnType("text")
                        .HasColumnName("detalhe");

                    b.Property<int?>("DocumentoId")
                        .HasColumnType("integer")
                        .HasColumnName("documento_id");

                    b.Property<int?>("EnvioId")
                        .HasColumnType("integer")
                        .HasColumnName("envio_id");

                    b.Property<bool>("Lido")
                        .HasColumnType("boolean")
                        .HasColumnName("lido");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensagem");

                    b.Property<AlertaTipo>("Tipo")
                        .HasColumnType("alerta_tipo")
                        .HasColumnName("tipo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("EnvioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("alertas");
                });

            modelBuilder.Entity("Accusoft.Api.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("acao");

                    b.Property<int>("AdminId")
                        .HasColumnType("integer")
                        .HasColumnName("admin_id");

                    b.Property<string>("Detalhe")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalhe");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Devolucao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataDevolucao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_devolucao");

                    b.Property<int?>("EntradaId")
                        .HasColumnType("integer")
                        .HasColumnName("entrada_id");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("integer")
                        .HasColumnName("fornecedor_id");

                    b.Property<string>("MotivoGeral")
                        .HasColumnType("text")
                        .HasColumnName("motivo_geral");

                    b.Property<string>("NumeroDevolucao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_devolucao");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<int?>("OrdemCompraId")
                        .HasColumnType("integer")
                        .HasColumnName("ordem_compra_id");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("prioridade");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.HasIndex("EntradaId");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("NumeroDevolucao")
                        .IsUnique();

                    b.HasIndex("OrdemCompraId");

                    b.HasIndex("Status");

                    b.HasIndex("UsuarioId");

                    b.ToTable("devolucoes");
                });

            modelBuilder.Entity("Accusoft.Api.Models.DevolucaoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DevolucaoId")
                        .HasColumnType("integer")
                        .HasColumnName("devolucao_id");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("localizacao");

                    b.Property<string>("Lote")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lote");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<int>("QuantidadeAprovada")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_aprovada");

                    b.Property<int>("QuantidadeRejeitada")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_rejeitada");

                    b.HasKey("Id");

                    b.HasIndex("DevolucaoId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("devolucao_itens");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("DataAbertura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_abertura");

                    b.Property<DateTimeOffset>("DataUpload")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_upload");

                    b.Property<int?>("EnvioId")
                        .HasColumnType("integer")
                        .HasColumnName("envio_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("nome");

                    b.Property<string>("PathUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path_url");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_bytes");

                    b.Property<DocTipo>("Tipo")
                        .HasColumnType("doc_tipo")
                        .HasColumnName("tipo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("EnvioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("documentos");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Entrada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("AcomodadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acomodado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_entrada");

                    b.Property<string>("Fornecedor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("fornecedor");

                    b.Property<int?>("LpnId")
                        .HasColumnType("integer")
                        .HasColumnName("lpn_id");

                    b.Property<string>("NumeroEntrada")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_entrada");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<int?>("OrdemCompraId")
                        .HasColumnType("integer")
                        .HasColumnName("ordem_compra_id");

                    b.Property<string>("Protocolo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("protocolo");

                    b.Property<DateTimeOffset?>("RecebidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recebido_em");

                    b.Property<string>("RtmStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rtm_status");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("TipoEntrada")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_entrada");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<string>("ZonaRecepcao")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("zona_recepcao");

                    b.HasKey("Id");

                    b.HasIndex("LpnId");

                    b.HasIndex("NumeroEntrada")
                        .IsUnique();

                    b.HasIndex("OrdemCompraId");

                    b.HasIndex("RtmStatus");

                    b.HasIndex("Status");

                    b.HasIndex("UsuarioId");

                    b.ToTable("entradas");
                });

            modelBuilder.Entity("Accusoft.Api.Models.EntradaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Armazem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("armazem");

                    b.Property<bool>("Conferido")
                        .HasColumnType("boolean")
                        .HasColumnName("conferido");

                    b.Property<int>("Diferenca")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasColumnName("diferenca");

                    b.Property<int>("EntradaId")
                        .HasColumnType("integer")
                        .HasColumnName("entrada_id");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("localizacao");

                    b.Property<string>("Lote")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lote");

                    b.Property<int?>("LpnId")
                        .HasColumnType("integer")
                        .HasColumnName("lpn_id");

                    b.Property<string>("MotivoDivergencia")
                        .HasColumnType("text")
                        .HasColumnName("motivo_divergencia");

                    b.Property<string>("MotivoNaoConformidade")
                        .HasColumnType("text")
                        .HasColumnName("motivo_nao_conformidade");

                    b.Property<bool>("NaoConformidade")
                        .HasColumnType("boolean")
                        .HasColumnName("nao_conformidade");

                    b.Property<string>("ProdutoNome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("produto_nome");

                    b.Property<int>("QuantidadeAceite")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_aceite");

                    b.Property<int>("QuantidadeContada")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_contada");

                    b.Property<int>("QuantidadeDevolvida")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_devolvida");

                    b.Property<int>("QuantidadeEsperada")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_esperada");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<bool>("TemDivergencia")
                        .HasColumnType("boolean")
                        .HasColumnName("tem_divergencia");

                    b.Property<DateOnly?>("Validade")
                        .HasColumnType("date")
                        .HasColumnName("validade");

                    b.HasKey("Id");

                    b.HasIndex("EntradaId");

                    b.HasIndex("LpnId");

                    b.HasIndex("Sku");

                    b.ToTable("entrada_itens");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Envio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<DateOnly>("DataPrevista")
                        .HasColumnType("date")
                        .HasColumnName("data_prevista");

                    b.Property<EnvioEstado>("Estado")
                        .HasColumnType("envio_estado")
                        .HasColumnName("estado");

                    b.Property<string>("IdString")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("id_string");

                    b.Property<string>("NomeEquipamento")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("nome_equipamento");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("IdString")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("envios");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Estoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("location");

                    b.Property<string>("LotNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lot_number");

                    b.Property<decimal>("PickingQty")
                        .HasColumnType("numeric")
                        .HasColumnName("picking_qty");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<decimal>("ReservedQty")
                        .HasColumnType("numeric")
                        .HasColumnName("reserved_qty");

                    b.Property<string>("Warehouse")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("warehouse");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId", "Warehouse", "Location", "LotNumber")
                        .IsUnique();

                    b.ToTable("estoque");
                });

            modelBuilder.Entity("Accusoft.Api.Models.ExpedicaoRascunho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Destinatario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("destinatario");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("boolean")
                        .HasColumnName("finalizado");

                    b.Property<string>("LinhasJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("linhas_json");

                    b.Property<string>("NumeroEncomenda")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("numero_encomenda");

                    b.Property<string>("Transportadora")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transportadora");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("expedicao_rascunhos");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Contacto")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contacto");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("Morada")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("morada");

                    b.Property<string>("Nif")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nif");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("Nif");

                    b.HasIndex("Nome");

                    b.ToTable("fornecedores");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("ClienteContacto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cliente_contacto");

                    b.Property<string>("ClienteEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cliente_email");

                    b.Property<string>("ClienteMorada")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("cliente_morada");

                    b.Property<string>("ClienteNif")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cliente_nif");

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cliente_nome");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataDoc")
                        .HasColumnType("date")
                        .HasColumnName("data_doc");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado");

                    b.Property<decimal?>("HorasTrabalho")
                        .HasColumnType("numeric")
                        .HasColumnName("horas_trabalho");

                    b.Property<string>("MaterialUtilizado")
                        .HasColumnType("text")
                        .HasColumnName("material_utilizado");

                    b.Property<string>("NumeroFatura")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_fatura");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("QuemExecutou")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("quem_executou");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("faturas");
                });

            modelBuilder.Entity("Accusoft.Api.Models.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cor");

                    b.Property<int>("FaturaId")
                        .HasColumnType("integer")
                        .HasColumnName("fatura_id");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("marca");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("matricula");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modelo");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("subtotal");

                    b.HasKey("Id");

                    b.HasIndex("FaturaId");

                    b.ToTable("fatura_itens");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Lpn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Armazem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("armazem");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("localizacao");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("UsuarioId");

                    b.ToTable("lpns");
                });

            modelBuilder.Entity("Accusoft.Api.Models.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DataMov")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_mov");

                    b.Property<int>("EstoqueId")
                        .HasColumnType("integer")
                        .HasColumnName("estoque_id");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("numeric")
                        .HasColumnName("quantidade");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("EstoqueId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("movimentacoes_estoque");
                });

            modelBuilder.Entity("Accusoft.Api.Models.OrdemCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataEmissao")
                        .HasColumnType("date")
                        .HasColumnName("data_emissao");

                    b.Property<DateOnly?>("DataPrevista")
                        .HasColumnType("date")
                        .HasColumnName("data_prevista");

                    b.Property<int>("FornecedorId")
                        .HasColumnType("integer")
                        .HasColumnName("fornecedor_id");

                    b.Property<string>("NumeroOC")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_oc");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text")
                        .HasColumnName("observacoes");

                    b.Property<string>("Protocolo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("protocolo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("NumeroOC")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ordens_compra");
                });

            modelBuilder.Entity("Accusoft.Api.Models.OrdemCompraItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OrdemCompraId")
                        .HasColumnType("integer")
                        .HasColumnName("ordem_compra_id");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<int>("QuantidadeRecebida")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_recebida");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("subtotal");

                    b.HasKey("Id");

                    b.HasIndex("OrdemCompraId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ordens_compra_itens");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("MinLevel")
                        .HasColumnType("integer")
                        .HasColumnName("min_level");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("nome");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.HasKey("Id");

                    b.ToTable("produtos");
                });

            modelBuilder.Entity("Accusoft.Api.Models.RececaoRascunho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Finalizado")
                        .HasColumnType("boolean")
                        .HasColumnName("finalizado");

                    b.Property<string>("LinhasJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("linhas_json");

                    b.Property<string>("ReferenciaDocumento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("referencia_documento");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("rececao_rascunhos");
                });

            modelBuilder.Entity("Accusoft.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cargo");

                    b.Property<DateTimeOffset>("DataCriacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("departamento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<UserRole>("Role")
                        .HasColumnType("user_role")
                        .HasColumnName("role");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.Property<UserStatus>("Status")
                        .HasColumnType("user_status")
                        .HasColumnName("status");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefone");

                    b.Property<DateTimeOffset?>("UltimoLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_login");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Alerta", b =>
                {
                    b.HasOne("Accusoft.Api.Models.Documento", "Documento")
                        .WithMany("Alertas")
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Accusoft.Api.Models.Envio", "Envio")
                        .WithMany("Alertas")
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Accusoft.Api.Models.User", "Usuario")
                        .WithMany("Alertas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");

                    b.Navigation("Envio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Accusoft.Api.Models.AuditLog", b =>
                {
                    b.HasOne("Accusoft.Api.Models.User", "Admin")
                        .WithMany("AuditLogs")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Devolucao", b =>
                {
                    b.HasOne("Accusoft.Api.Models.Entrada", "Entrada")
                        .WithMany()
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Accusoft.Api.Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Accusoft.Api.Models.OrdemCompra", "OrdemCompra")
                        .WithMany()
                        .HasForeignKey("OrdemCompraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Accusoft.Api.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrada");

                    b.Navigation("Fornecedor");

                    b.Navigation("OrdemCompra");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Accusoft.Api.Models.DevolucaoItem", b =>
                {
                    b.HasOne("Accusoft.Api.Models.Devolucao", "Devolucao")
                        .WithMany("Itens")
                        .HasForeignKey("DevolucaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accusoft.Api.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Devolucao");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Documento", b =>
                {
                    b.HasOne("Accusoft.Api.Models.Envio", "Envio")
                        .WithMany("Documentos")
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Accusoft.Api.Models.User", "Usuario")
                        .WithMany("Documentos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Envio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Entrada", b =>
                {
                    b.HasOne("Accusoft.Api.Models.Lpn", "Lpn")
                        .WithMany()
                        .HasForeignKey("LpnId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Accusoft.Api.Models.OrdemCompra", "OrdemCompra")
                        .WithMany()
                        .HasForeignKey("OrdemCompraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Accusoft.Api.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lpn");

                    b.Navigation("OrdemCompra");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Accusoft.Api.Models.EntradaItem", b =>
                {
                    b.HasOne("Accusoft.Api.Models.Entrada", "Entrada")
                        .WithMany("Itens")
                        .HasForeignKey("EntradaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accusoft.Api.Models.Lpn", "Lpn")
                        .WithMany()
                        .HasForeignKey("LpnId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Entrada");

                    b.Navigation("Lpn");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Envio", b =>
                {
                    b.HasOne("Accusoft.Api.Models.User", "Usuario")
                        .WithMany("Envios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Estoque", b =>
                {
                    b.HasOne("Accusoft.Api.Models.Produto", "Produto")
                        .WithMany("Estoques")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Accusoft.Api.Models.ExpedicaoRascunho", b =>
                {
                    b.HasOne("Accusoft.Api.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Invoice", b =>
                {
                    b.HasOne("Accusoft.Api.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Accusoft.Api.Models.InvoiceItem", b =>
                {
                    b.HasOne("Accusoft.Api.Models.Invoice", "Fatura")
                        .WithMany("Itens")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Lpn", b =>
                {
                    b.HasOne("Accusoft.Api.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Accusoft.Api.Models.MovimentacaoEstoque", b =>
                {
                    b.HasOne("Accusoft.Api.Models.Estoque", "Estoque")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("EstoqueId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Accusoft.Api.Models.Produto", "Produto")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Accusoft.Api.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Estoque");

                    b.Navigation("Produto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Accusoft.Api.Models.OrdemCompra", b =>
                {
                    b.HasOne("Accusoft.Api.Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Accusoft.Api.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Accusoft.Api.Models.OrdemCompraItem", b =>
                {
                    b.HasOne("Accusoft.Api.Models.OrdemCompra", "OrdemCompra")
                        .WithMany("Itens")
                        .HasForeignKey("OrdemCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Accusoft.Api.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdemCompra");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Accusoft.Api.Models.RececaoRascunho", b =>
                {
                    b.HasOne("Accusoft.Api.Models.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Devolucao", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Documento", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Entrada", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Envio", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Estoque", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Invoice", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Accusoft.Api.Models.OrdemCompra", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Accusoft.Api.Models.Produto", b =>
                {
                    b.Navigation("Estoques");

                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("Accusoft.Api.Models.User", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("AuditLogs");

                    b.Navigation("Documentos");

                    b.Navigation("Envios");
                });
#pragma warning restore 612, 618
        }
    }
}
